# define DWM_BORDERPX 1
# define DWM_SNAP 32
# define DWM_SHOWBAR 1
# define DWM_TOPBAR 1
# define DWM_FONT {"monospace:size=10"}
# define DWM_FOREGROUND "#93a1a1"
# define DWM_BACKGROUND "#002b36"
# define DWM_BORDER "#93a1a1"
# define DWM_SELFOREGROUND "#073642"
# define DWM_SELBACKGROUND "#2aa198"
# define DWM_SELBORDER "#cb4b16"
