#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

 if [ -f ~/.xmodmap ]; then
     xmodmap ~/.xmodmap
 fi


if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#twm &
#xclock -geometry 50x50-1+1 &
#xterm -geometry 80x50+494+51 &
#xterm -geometry 80x20+494-0 &
#exec xterm -geometry 80x66+0+0 -name login
#
#exec dwm

##################
## My Conf's
##################
#### KeyboardLayout
#keyboardchlayout &
#
####### Lang ######
export LC_ALL=en_US.UTF-8
export MM_CHARSET=UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export BROWSER=firefox
#setxkbmap us
export QT_QPA_PLATFORMTHEME="qt5ct"
MOZ_X11_EGL=1
xset s off
xset -dpms
xset s noblank
#xautolock -time 10 -locker slock
export GVFS_DISABLE_FUSE=1

####################
### Nvidia ##
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto

### KL
setxkbmap -model apple_laptop -layout us,ara -option grp:alt_shift_toggle &


autowall &

dinit -q &

### Pywal ###
# Add this to your .xinitrc or whatever file starts programs on startup.
# -R restores the last colorscheme that was in use.
wal -R

##xrandr --setprovideroutputsource modesetting NVIDIA-0
##xrandr --auto

#### DWM ###
while :; do
	ssh-agent dwm
done
#exec dwm
#dbus-run-session
###




